const ASCII = new TextDecoder('ascii')

function isWhitespace(value) {
  return value === 9 || value === 10 || value === 13 || value === 32
}

function readToken(bytes, state) {
  while (state.index < bytes.length) {
    if (isWhitespace(bytes[state.index])) {
      state.index += 1
      continue
    }
    if (bytes[state.index] === 35) {
      while (state.index < bytes.length && bytes[state.index] !== 10) state.index += 1
      continue
    }
    break
  }

  const start = state.index
  while (
    state.index < bytes.length
    && !isWhitespace(bytes[state.index])
    && bytes[state.index] !== 35
  ) {
    state.index += 1
  }

  if (start === state.index) throw new Error('PGM 文件头不完整')
  return ASCII.decode(bytes.subarray(start, state.index))
}

function normalizeSample(value, maxValue) {
  return Math.max(0, Math.min(255, Math.round((value / maxValue) * 255)))
}

export function parsePgm(buffer) {
  const bytes = buffer instanceof Uint8Array ? buffer : new Uint8Array(buffer)
  const state = { index: 0 }
  const magic = readToken(bytes, state)
  if (magic !== 'P2' && magic !== 'P5') {
    throw new Error('仅支持 P2 或 P5 灰度 PGM 文件')
  }

  const width = Number(readToken(bytes, state))
  const height = Number(readToken(bytes, state))
  const maxValue = Number(readToken(bytes, state))
  if (!Number.isInteger(width) || !Number.isInteger(height) || width <= 0 || height <= 0) {
    throw new Error('PGM 尺寸无效')
  }
  if (!Number.isInteger(maxValue) || maxValue <= 0 || maxValue > 65535) {
    throw new Error('PGM 最大灰度值无效')
  }
  if (width * height > 16_000_000) throw new Error('地图像素超过 1600 万，暂不支持')

  const pixels = new Uint8Array(width * height)
  if (magic === 'P2') {
    for (let index = 0; index < pixels.length; index += 1) {
      const value = Number(readToken(bytes, state))
      if (!Number.isFinite(value)) throw new Error(`PGM 在第 ${index + 1} 个像素处中断`)
      pixels[index] = normalizeSample(value, maxValue)
    }
  } else {
    if (!isWhitespace(bytes[state.index])) throw new Error('PGM 文件头缺少分隔符')
    const firstSeparator = bytes[state.index]
    state.index += 1
    if (firstSeparator === 13 && bytes[state.index] === 10) state.index += 1

    const bytesPerSample = maxValue < 256 ? 1 : 2
    const expectedBytes = pixels.length * bytesPerSample
    if (bytes.length - state.index < expectedBytes) throw new Error('PGM 像素数据不完整')

    for (let index = 0; index < pixels.length; index += 1) {
      const offset = state.index + index * bytesPerSample
      const value = bytesPerSample === 1
        ? bytes[offset]
        : (bytes[offset] << 8) | bytes[offset + 1]
      pixels[index] = normalizeSample(value, maxValue)
    }
  }

  return { width, height, pixels, format: magic, maxValue }
}

export function encodePgm(width, height, pixels, comment = 'Generated by Map Zone Painter Web') {
  if (pixels.length !== width * height) throw new Error('输出像素数量与地图尺寸不一致')
  const header = new TextEncoder().encode(`P5\n# ${comment}\n${width} ${height}\n255\n`)
  const output = new Uint8Array(header.length + pixels.length)
  output.set(header)
  output.set(pixels, header.length)
  return output
}

const CRC_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let index = 0; index < 256; index += 1) {
    let value = index
    for (let bit = 0; bit < 8; bit += 1) {
      value = (value & 1) ? 0xedb88320 ^ (value >>> 1) : value >>> 1
    }
    table[index] = value >>> 0
  }
  return table
})()

function crc32(bytes) {
  let crc = 0xffffffff
  for (const byte of bytes) crc = CRC_TABLE[(crc ^ byte) & 0xff] ^ (crc >>> 8)
  return (crc ^ 0xffffffff) >>> 0
}

function concatBytes(parts) {
  const length = parts.reduce((total, part) => total + part.length, 0)
  const output = new Uint8Array(length)
  let offset = 0
  for (const part of parts) {
    output.set(part, offset)
    offset += part.length
  }
  return output
}

export function encodeZip(entries) {
  const encoder = new TextEncoder()
  const localParts = []
  const centralParts = []
  let localOffset = 0

  for (const entry of entries) {
    const name = encoder.encode(entry.name)
    const data = entry.data instanceof Uint8Array ? entry.data : new Uint8Array(entry.data)
    const checksum = crc32(data)

    const localHeader = new Uint8Array(30)
    const localView = new DataView(localHeader.buffer)
    localView.setUint32(0, 0x04034b50, true)
    localView.setUint16(4, 20, true)
    localView.setUint16(6, 0x0800, true)
    localView.setUint16(8, 0, true)
    localView.setUint32(14, checksum, true)
    localView.setUint32(18, data.length, true)
    localView.setUint32(22, data.length, true)
    localView.setUint16(26, name.length, true)
    localParts.push(localHeader, name, data)

    const centralHeader = new Uint8Array(46)
    const centralView = new DataView(centralHeader.buffer)
    centralView.setUint32(0, 0x02014b50, true)
    centralView.setUint16(4, 20, true)
    centralView.setUint16(6, 20, true)
    centralView.setUint16(8, 0x0800, true)
    centralView.setUint16(10, 0, true)
    centralView.setUint32(16, checksum, true)
    centralView.setUint32(20, data.length, true)
    centralView.setUint32(24, data.length, true)
    centralView.setUint16(28, name.length, true)
    centralView.setUint32(42, localOffset, true)
    centralParts.push(centralHeader, name)

    localOffset += localHeader.length + name.length + data.length
  }

  const localData = concatBytes(localParts)
  const centralData = concatBytes(centralParts)
  const end = new Uint8Array(22)
  const endView = new DataView(end.buffer)
  endView.setUint32(0, 0x06054b50, true)
  endView.setUint16(8, entries.length, true)
  endView.setUint16(10, entries.length, true)
  endView.setUint32(12, centralData.length, true)
  endView.setUint32(16, localData.length, true)
  return concatBytes([localData, centralData, end])
}

export function buildMaskOutputs(base, keepMask, speedMask) {
  if (base.length !== keepMask.length || base.length !== speedMask.length) {
    throw new Error('掩码尺寸与原始地图不一致')
  }

  const keepout = base.slice()
  const speed = base.slice()
  let keepoutPixels = 0
  let speedPixels = 0
  let overlapPixels = 0

  for (let index = 0; index < base.length; index += 1) {
    if (keepMask[index]) {
      keepout[index] = 0
      keepoutPixels += 1
    }
    if (speedMask[index] && !keepMask[index]) {
      speed[index] = 128
      speedPixels += 1
    }
    if (keepMask[index] && speedMask[index]) overlapPixels += 1
    if (speed[index] === 0) speed[index] = 255
  }

  return {
    keepout,
    speed,
    stats: { keepoutPixels, speedPixels, overlapPixels },
  }
}

export function paintCircle(mask, width, height, centerX, centerY, radius, value) {
  const minX = Math.max(0, Math.floor(centerX - radius))
  const maxX = Math.min(width - 1, Math.ceil(centerX + radius))
  const minY = Math.max(0, Math.floor(centerY - radius))
  const maxY = Math.min(height - 1, Math.ceil(centerY + radius))
  const radiusSquared = radius * radius

  for (let y = minY; y <= maxY; y += 1) {
    for (let x = minX; x <= maxX; x += 1) {
      const dx = x - centerX
      const dy = y - centerY
      if (dx * dx + dy * dy <= radiusSquared) mask[y * width + x] = value
    }
  }
}

export function paintLine(mask, width, height, from, to, radius, value) {
  const distance = Math.hypot(to.x - from.x, to.y - from.y)
  const steps = Math.max(1, Math.ceil(distance / Math.max(1, radius * 0.45)))
  for (let step = 0; step <= steps; step += 1) {
    const progress = step / steps
    paintCircle(
      mask,
      width,
      height,
      from.x + (to.x - from.x) * progress,
      from.y + (to.y - from.y) * progress,
      radius,
      value,
    )
  }
}

export function fillPolygon(mask, width, height, points, value) {
  if (points.length < 3) return
  const minY = Math.max(0, Math.floor(Math.min(...points.map(point => point.y))))
  const maxY = Math.min(height - 1, Math.ceil(Math.max(...points.map(point => point.y))))

  for (let y = minY; y <= maxY; y += 1) {
    const scanY = y + 0.5
    const intersections = []
    for (let index = 0; index < points.length; index += 1) {
      const current = points[index]
      const next = points[(index + 1) % points.length]
      if ((current.y <= scanY && next.y > scanY) || (next.y <= scanY && current.y > scanY)) {
        const ratio = (scanY - current.y) / (next.y - current.y)
        intersections.push(current.x + ratio * (next.x - current.x))
      }
    }
    intersections.sort((a, b) => a - b)
    for (let index = 0; index + 1 < intersections.length; index += 2) {
      const startX = Math.max(0, Math.ceil(intersections[index]))
      const endX = Math.min(width - 1, Math.floor(intersections[index + 1]))
      for (let x = startX; x <= endX; x += 1) mask[y * width + x] = value
    }
  }
}

export function createDemoMap(width = 360, height = 240) {
  const pixels = new Uint8Array(width * height).fill(254)
  const drawRect = (x, y, rectWidth, rectHeight, value = 0) => {
    for (let py = Math.max(0, y); py < Math.min(height, y + rectHeight); py += 1) {
      for (let px = Math.max(0, x); px < Math.min(width, x + rectWidth); px += 1) {
        pixels[py * width + px] = value
      }
    }
  }

  drawRect(0, 0, width, 6)
  drawRect(0, height - 6, width, 6)
  drawRect(0, 0, 6, height)
  drawRect(width - 6, 0, 6, height)
  drawRect(72, 0, 6, 78)
  drawRect(72, 108, 6, 76)
  drawRect(72, 178, 116, 6)
  drawRect(182, 92, 6, 92)
  drawRect(182, 92, 88, 6)
  drawRect(264, 40, 6, 58)
  drawRect(264, 128, 6, 112)
  drawRect(270, 128, 90, 6)
  drawRect(22, 30, 26, 18, 205)
  drawRect(294, 170, 38, 30, 205)

  return { width, height, pixels, format: 'P5', maxValue: 255 }
}
